### ISSUE TITLE
Not working when default branch is not master

### ISSUE THREAD

**Issue by saurabtanej** [semaphoreci-demos/semaphore-demo-monorepo#15]
Something is wrong and it's not working for me. I've tried multiple Permutations and Combinations. 

I am trying to do the monorepo with `when` and `change_in` but it's not working. It triggers all the jobs for me all the time. It doesn't matter if there is a change in the directory or not. It triggers all the jobs. 

Here is my yaml:

```
version: "v1.0"
name: Monorepo project
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  # Run this block on changes in the web-app folder at the root of the repository
  - name: Test rainforest App
    dependencies: []
    run:
      when: "change_in('/apps/rainforest', {default_branch: 'main'}, {pipeline_file: 'ignore'})"
    task:
      jobs:
        - commands:
            - echo "$PWD"

  # Run this block on changes in the ios folder at the root of the repository
  - name: run rainforest-qa for blueprint
    dependencies: []
    run:
      when: "change_in('/apps/blueprint', {default_branch: 'main'}, {pipeline_file: 'ignore'})"
    task:
      jobs:
        - commands:
            - echo "$PWD"

  # Run this block on changes in the docs folder at the root of the repository
  - name: run rainforest-qa for login
    dependencies: []
    run:
      when: "change_in('/apps/login', {default_branch: 'main'}, {pipeline_file: 'ignore'})"
    task:
      jobs:
        - commands:
            - echo "$PWD"

  # Run this block on changes in web-app or ios folders at the root of the repository
  - name: run rainforest-qa for secure
    dependencies: []
    run:
      when: "change_in('/apps/secure', {default_branch: 'main'}, {pipeline_file: 'ignore'})"
    task:
      jobs:
        - commands:
            - echo "$PWD"

  - name: run rainforest-qa for lenders
    dependencies: []
    run:
      when: "change_in('/apps/lenders', {default_branch: 'main'}, {pipeline_file: 'ignore'})"
    task:
      jobs:
        - commands:
            - echo "$PWD"

promotions:
  - name: Deploy to production
    pipeline_file: deploy_production.yml
    auto_promote:
      when: "result = 'passed' and branch = 'saurabh-test'"
  - name: Deploy to testing
    pipeline_file: deploy_testing.yml
```
